"""score table2

Revision ID: 67c230744b7c
Revises: d88fb96df13d
Create Date: 2022-05-10 17:38:50.610112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c230744b7c'
down_revision = 'd88fb96df13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Score', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('Score', sa.Column('cum_points', sa.Integer(), nullable=True))
    op.add_column('Score', sa.Column('games_played', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Score', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Score', type_='foreignkey')
    op.drop_column('Score', 'games_played')
    op.drop_column('Score', 'cum_points')
    op.drop_column('Score', 'user_id')
    # ### end Alembic commands ###
